config/routes.rb
SmallGroup::Application.routes.draw do

   root 'home#index'

   get 'members/names_for_today' => 'members#names_for_today'
   get 'members/prayer_email' => 'members#prayer_email'
   get 'members/get_members' => 'members#get_members'
   resources :members

end

app/models/member.rb
class Member
	include Mongoid::Document
	field :name, type: String
	field :days, type: Array
	field :email, type: String
	field :phone, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index

	end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	def index
		@members = Member.asc(:name)
	end

	def new
		@member = Member.new
		@member.days = []
		@days = get_days

	end

	def edit
		@member = Member.find(params[:id])
		@days = get_days
	end

	def create
		@member = Member.new(member_params)

		if @member.save
			redirect_to members_path
		else
			@days = get_days
			render :new
		end
	end

	def update
		@member = Member.find(params[:id])

		if @member.update_attributes(member_params)
			redirect_to members_path
		else
			@days = get_days
			render :edit
		end
	end

	def destroy
		@member = Member.find(params[:id])
		@member.destroy

		redirect_to members_path
	end

	def get_days
		["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
	end

	def names_for_today
		today = Time.now.strftime("%a")

		names = Member.asc(:name).select {|n| n.days.any? {|d| d == today}}.map { |m| m.name }

		render json: names

	end

	def prayer_email
		@names = Member.all.pluck(:email)
		PrayerList.prayer_email(@names).deliver

		render :json => {:success => "true"}
	end

	def get_members
		@names = Member.asc(:name)

		render :json => {:names => @names}
	end


	private
		def member_params
			params.require(:member).permit(:name, :email, :phone, :days => [])

		end


end

app/controllers/schedule_controller.rb
class ScheduleController < ApplicationController
	def index

	end

	def new

	end

	def edit

	end

	def save

	end

	def update

	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/member_helper.rb
module MemberHelper
	def day_selected(day, member)
		member.days.any? {|d| d == day}
	end

	def days_string(member)
		return "" if member.days.nil?

		member.days.join(", ")
	end


end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/home/index.html.erb
Test

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Small Group" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">SmallGroup</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Members", members_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/members/edit.html.erb
<%= form_for @member do |m| %>
	<fieldset>
		<legend>Edit <%= @member.name %></legend>

		<div class="control-group">
			<%= m.label :name, :class => "control-group" %>
			<%= m.text_field :name, :class => "form-control" %>
		</div>	

		<div class="control-group">
			<%= m.label :email, :class => "control-group" %>
			<%= m.text_field :email, :class => "form-control" %>
		</div>	

		<div class="control-group">
			<%= m.label :phone, :class => "control-group" %>
			<%= m.text_field :phone, :class => "form-control" %>
		</div>	

		<div>
			<% @days.each do |d| %>
				<%= check_box_tag 'member[days][]', d, day_selected(d, @member) %>
				<%= d %>

			<% end %>
		</div>

	<%= m.submit :class => "btn btn-primary" %>

	</fieldset>


<% end %>

app/views/members/index.html.erb
<%= link_to "New", new_member_path, :class => "btn btn-primary" %>

<table class="table">
	<thead>
		<tr>
			<th>Name</th>
			<th>Prayer Days</th>
			<th>Actions</th>
		</tr>
	</thead>
	
	<tbody>
		<% @members.each do |m| %>
			<tr>
				<td><%= m.name %></td>
				<td><%= days_string(m) %></td>
				<td>
					<div class="btn-group">
						<%= link_to 'Edit', edit_member_path(m), :class => "btn" %>
						<%= link_to 'Delete', member_path(m), :method => :delete, :class => 'btn btn-danger' %>
					</div>
				</td>

			</tr>
		<% end %>

	</tbody>

</table>

app/views/members/new.html.erb
<%= form_for @member do |m| %>
	<fieldset>
		<legend>New Member</legend>

		<div class="control-group">
			<%= m.label :name, :class => "control-group" %>
			<%= m.text_field :name, :class => "form-control" %>
		</div>	

		<div class="control-group">
			<%= m.label :email, :class => "control-group" %>
			<%= m.text_field :email, :class => "form-control" %>
		</div>	

		<div class="control-group">
			<%= m.label :phone, :class => "control-group" %>
			<%= m.text_field :phone, :class => "form-control" %>
		</div>	

		<div>
			<% @days.each do |d| %>
				<%= check_box_tag 'member[days][]', d, day_selected(d, @member) %>
				<%= d %>

			<% end %>
		</div>

	<%= m.submit :class => "btn btn-primary" %>

	</fieldset>


<% end %>

app/views/prayer_list/prayer_email.html.erb
test me